# This is a sample .typo-ci.yml file, it's used to configure how Typo CI will behave.
# Add it to the root of your project and push it to github.
---

# What language dictionaries should it use? By default Typo CI will select 'en' & 'en_GB'
# Currently Typo CI supports:
# de
# en
# en_GB
# es
# fr
# it
# nl
# pt
# pt_BR
# tr
dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"
  - ".github/.typo-ci.yml"
  - "*.gif"
  - ".github/**/*"

# Any words we should ignore?
excluded_words:
  - Eldev
  - defun
  - elisp
  - emacs
  - ess-command
  - rutils
  - rutils-packrat-status
  - rutils-renv-status
  - rutils-send--command-with-project
  - package
  - renv
  - typoci
  - wucuo
  - defsubst

# Would you like filenames to also be spellchecked?
spellcheck_filenames: false
